platform:ios, '8.0'

inhibit_all_warnings!

target 'GB_Video’ do
    use_frameworks!
    
pod 'Zip', '0.6.0'
pod 'MBProgressHUD', 		'0.9.2'
pod 'IQKeyboardManager',     '5.0.4'
pod 'EXTView', 			'0.1.0'
pod 'GDataXML-HTML', 		'1.3.0'
pod 'SDWebImage', 		'4.0.0'
pod 'pop', 			'1.0.9'
pod 'DZNEmptyDataSet', 		'1.8.1'
pod 'UMengAnalytics', 		'4.1.8'
pod 'RTLabel',			'1.0.1'
pod 'JPush', 			'3.0.2'
pod 'ShareSDK3',		'3.5.2'
pod 'MOBFoundation',    '3.0.1'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'ShareSDK3/ShareSDKExtension'
pod 'Masonry',      '1.0.2'
pod 'YYHCache'

end
