# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarOilSupermarket' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CarOilSupermarket
pod ‘YHCommon’, '0.6'
pod 'YYHCache'
pod 'IQKeyboardManager', 	'5.0.4'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'ViewDeck', '2.4.1'
pod 'SDCycleScrollView', '1.66'
pod 'AFNetworking'
pod 'YAHMultiPhoto', '0.0.5'
pod 'GDataXML-HTML', 		'1.3.0'

end
